name: image
on:
  push:
    tags:
    - '*'
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - name: Configure envvars
      run: |
        TAGS=$(
          for repository in quay.io/jcmoraisjr jcmoraisjr; do
            for project in dory; do
              for tag in "${GITHUB_REF#refs/tags/}" latest; do
                echo -n "${repository}/${project}:${tag},"
              done
            done
          done
        )
        echo "TAGS=$TAGS" >> $GITHUB_ENV
    - uses: actions/checkout@v2
    - uses: docker/login-action@v1 
      with:
        username: jcmoraisjr
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: docker/login-action@v1 
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_TOKEN }}
    - uses: docker/setup-buildx-action@v1
    - uses: docker/build-push-action@v2
      with:
        context: .
        file: builder/Dockerfile
        platforms: linux/amd64
        push: true
        tags: ${{ env.TAGS }}
